// PC で旬パスを開いた利用者がスマホへ移るための、サイトURLのQRコードを作る。
// 実行時に生成するとQRエンコーダを実行時依存に足すことになるが、URLは固定なので事前生成に倒し、
// 生成物（public/site-url-qr.svg）をコミットする。
//
// URL を変えたら `npm run gen-site-qr` を叩き直すこと。
// 生成物と src/lib/site-config.ts のずれは tsc / lint / build のいずれでも検出できない。
//
// エンコーダは barcode-detector の推移的依存として既に入っている zxing-wasm の writer を使う
// （sync-zxing-wasm.mjs が node_modules の実体を直接読んでいるのと同じ前提に乗っている）。
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { prepareZXingModule, writeBarcode } from 'zxing-wasm/writer';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// src/lib/site-config.ts の DEFAULT_SITE_URL と揃えること。
// .mjs から TS を読めないため重複するが、参照先だけは明示しておく。
const DEFAULT_SITE_URL = 'https://shunpass.vercel.app';

// .env.local はこのスクリプトでは読まれない。別のURLで生成したいときは引数で渡す。
const url = process.argv[2] ?? process.env.NEXT_PUBLIC_SHUNPASS_SITE_URL ?? DEFAULT_SITE_URL;

// zxing-wasm は既定で .wasm を jsDelivr CDN から取りに行く。オフラインでも生成できるよう
// node_modules の実体を読んで渡す（qr-detector.ts で locateFile を差し替えているのと同じ理由）。
const wasmBinary = await readFile(
  resolve(projectRoot, 'node_modules/zxing-wasm/dist/writer/zxing_writer.wasm'),
);
await prepareZXingModule({ overrides: { wasmBinary }, fireImmediately: true });

const { svg, error } = await writeBarcode(url, { format: 'QRCode', ecLevel: 'M', scale: 1 });
if (error !== '') {
  throw new Error(`failed to encode QR: ${error}`);
}

// zxing の出力は <svg width="37" height="37"> で viewBox を持たず、SVG 1.1 の DOCTYPE が付く。
// そのままだと CSS 側で寸法を決められないため、前置きを落として viewBox に置き換える。
const withoutPreamble = svg.replace(/^[\s\S]*?(?=<svg )/, '');
let moduleCount = 0;
const withViewBox = withoutPreamble.replace(
  /^<svg width="(\d+)" height="(\d+)"/,
  (_match, width, height) => {
    moduleCount = Number(width);
    return `<svg viewBox="0 0 ${width} ${height}"`;
  },
);
if (moduleCount === 0) {
  throw new Error('unexpected svg header from the zxing writer');
}

const destination = resolve(projectRoot, 'public/site-url-qr.svg');
const output = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  `<!-- generated by \`npm run gen-site-qr\` from ${url} -->`,
  withViewBox,
].join('\n');

await writeFile(destination, output, 'utf8');

process.stdout.write(`generated ${destination}\n`);
process.stdout.write(`  url: ${url}\n`);
process.stdout.write(`  size: ${moduleCount}x${moduleCount} modules (quiet zone included)\n`);
